<?php

/**
 * Copyright (c) 2018 Justin Kuenzel (jukusoft.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/**
 * Project: JuKuCMS
 * License: Apache 2.0 license
 * User: Justin
 * Date: 23.03.2018
 * Time: 14:02
 */

class JSBuilder {

	protected $content = "";

	protected static $benchmark = array();
	
	public function __construct() {
		//
	}

	public function generateJS (string $style_name, string $media = "ALL", string $position = "header") {
		if (ACTIVATE_BENCHMARK) {
			$start_time = microtime(true);
		}

		//validate values
		$style_name = Validator_Filename::get($style_name);
		$media = strtoupper(Validator_Filename::get($media));
		$position = strtoupper(Validator_Filename::get($position));

		$suffix = "";

		if ($position !== "HEADER") {
			$suffix = "_" . strtolower($position);
		}

		$js_files = array();

		//get css files from style.json
		if (file_exists(STYLE_PATH . $style_name . "/style.json")) {
			$json = json_decode(file_get_contents(STYLE_PATH . $style_name . "/style.json"), true);

			if (isset($json['js' . $suffix]) && is_array($json['js' . $suffix])) {
				foreach ($json['js' . $suffix] as $js_file) {
					$full_path = STYLE_PATH . $style_name . "/" . $js_file;
					$js_files[] = $full_path;
				}
			}
		}

		//load js files from database
		$rows = Database::getInstance()->listRows("SELECT * FROM `{praefix}js_files` WHERE (`style` = :style OR `style` = 'ALL') AND (`media` = :media OR `media` = 'ALL') AND `position` = :position AND `activated` = '1'; ", array(
			'style' => $style_name,
			'media' => $media,
			'position' => $position
		));

		foreach ($rows as $row) {
			$js_files[] = $row['js_file'];
		}

		$buffer = "";

		foreach ($js_files as $js_file) {
			//first check, if file exists
			if (!file_exists($js_file)) {
				if (DEBUG_MODE) {
					echo "Coulnd't found javascript file (style: " . $style_name . "): " . $js_file;

					ob_end_flush();
					exit;
				} else {
					continue;
				}
			}

			//add file content to buffer
			$buffer .= file_get_contents($js_file) . "\n";
		}

		//$code = preg_replace("/\s\s+/", " ", $code);

		//https://github.com/matthiasmullie/minify

		//https://github.com/tchwork/jsqueeze

		//https://ourcodeworld.com/articles/read/350/how-to-minify-javascript-and-css-using-php

		//compress js: https://github.com/tedious/JShrink

		//remove comments
		//$buffer = preg_replace('!/\*[^*]*\*+([^/][^*]*\*+)*/!', '', $buffer);

		// remove space after colons
		//$buffer = str_replace(': ', ':', $buffer);

		//remove whitespace
		//$buffer = str_replace(array("\r\n", "\r", "\n", "\t", '  ', '    ', '    '), '', $buffer);

		//replace template variables
		$buffer = str_replace("{STYLE_PATH}", DomainUtils::getBaseURL() . "/styles/" . $style_name . "/", $buffer);

		//compress code
		$jz = new JSqueeze();
		$buffer = $jz->squeeze(
			$buffer,
			true,   // $singleLine
			false,   // $keepImportantComments
			false   // $specialVarRx
		);

		//set flag, if buffer is empty
		$empty_flag = empty($buffer);

		//add comment so md5 hash will change
		$buffer = "/* generated by jsbuilder on " . gmdate("D, d M Y H:i:s", time()) . ", empty flag: " . ($empty_flag ? "true" : "false") . " */" . $buffer;

		//create cache directory, if neccessary
		if (!file_exists(CACHE_PATH . "jsbuilder/")) {
			mkdir(CACHE_PATH . "jsbuilder/");
		}

		//cache buffer
		file_put_contents($this->getCachePath($style_name, $media, $position), $buffer);

		Cache::put("jsbuilder", "hash_" . $style_name . "_" . $media . "_" . strtolower($position), md5($buffer));
		Cache::put("jsbuilder", "meta_" . $style_name . "_" . $media . "_" . strtolower($position), array('empty_flag' => $empty_flag));

		$this->content = $buffer;

		if (ACTIVATE_BENCHMARK) {
			$end_time = microtime(true);
			$exec_time = $end_time - $start_time;

			self::$benchmark[$style_name . "_" . $media] = $exec_time;
		}

		return $buffer;
	}

	public function getCachePath (string $style, string $media = "ALL", string $position = "header") : string {
		$position = strtolower($position);

		$md5_filename = md5("js_" . $style . "_" . $media . "_" . $position);
		$js_cache_path = CACHE_PATH . "jsbuilder/" . $md5_filename . ".js";

		return $js_cache_path;
	}

	public function existsCache (string $style, string $media = "ALL", string $position = "header") : bool {
		return file_exists($this->getCachePath($style, $media, $position));
	}

	public function getHash (string $style, string $media = "ALL", string $position = "header") : string {
		if (!$this->existsCache($style, $media, $position)) {
			//generate cached js file
			$this->generateJS($style, $media, $position);
		}

		if (!Cache::contains("jsbuilder", "hash_" . $style . "_" . $media . "_" . $position)) {
			throw new IllegalStateException("cached js file 'hash_" . $style . "_" . $media . "_" . $position . "' doesnt exists.");
		}

		return Cache::get("jsbuilder", "hash_" . $style . "_" . $media . "_" . $position);
	}

	public function isEmpty (string $style, string $media = "ALL", string $position = "header") : bool {
		if (!Cache::contains("jsbuilder", "meta_" . $style . "_" . $media . "_" . $position)) {
			throw new IllegalStateException("cached js file 'meta_" . $style . "_" . $media . "_" . $position . "' doesnt exists.");
		}

		$array = Cache::get("jsbuilder", "meta_" . $style . "_" . $media . "_" . $position);

		return $array['empty_flag'];
	}

	public function load (string $style, string $media = "ALL", string $position = "header") {
		$cache_path = $this->getCachePath($style, $media, $position);

		if (!$this->existsCache($style, $media, $position)) {
			$this->generateJS($style, $media, $position);
		} else {
			$this->content = file_get_contents($cache_path);
		}
	}

	public function getBuffer () : string {
		return $this->content;
	}

	public static function listBenchmarks () {
		return self::$benchmark;
	}

}

?>
